### ISSUE TITLE
bvhrenamejoints example?

### ISSUE THREAD

**Issue by KristopherPeterson** [OlafHaag/bvh-toolbox#13]
Any possibility of adding an example or more documentation for renaming joints?

I see:

for row in csv_reader:
                mapping[row[0]] = row[1]

But no matter what I'm getting: NameError: name 'mapping' is not defined.

Thank you!

**Comment by OlafHaag** [comment]
Thanks for bringing this up, @KristopherPeterson !
You can get more detailed help if you type `bvhrenamejoints -h` on your command line.
Can you tell me the steps that caused this error?

You would need a CSV file that contains the old joint names and the new joint names.
e.g.
>pelvis,hip
>RightUpLeg,upper_leg_r

and so on.

**Comment by OlafHaag** [comment]
I was able to reproduce the error.

**Comment by KristopherPeterson** [comment]
Thanks for your fast reply! :+1: 

Here's my .csv:

RightUpLeg,RightHip
RightLeg,RightKnee
RightFoot,RightAnkle
LeftUpLeg,LeftHip
LeftLeg,LeftKnee
LeftFoot,LeftAnkle


And here's my console log:

D:\Mocap\BVH\Female\test>pip install bvhtoolbox
Requirement already satisfied: bvhtoolbox in c:\users\kristopher\appdata\local\p
rograms\python\python37-32\lib\site-packages (0.1.2)
Requirement already satisfied: transforms3d>=0.3.1 in c:\users\kristopher\appdat
a\local\programs\python\python37-32\lib\site-packages (from bvhtoolbox) (0.3.1)
Requirement already satisfied: numpy in c:\users\kristopher\appdata\local\progra
ms\python\python37-32\lib\site-packages (from bvhtoolbox) (1.19.4)
You are using pip version 18.1, however version 20.3b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

D:\Mocap\BVH\Female\test>bvhrenamejoints -h
usage: c:\users\kristopher\appdata\local\programs\python\python37-32\lib\site-pa
ckages\bvhtoolbox\manipulate\renamejoints.py
       [-h] [-v] [-o [OUT [OUT ...]]] input.bvh [input.bvh ...] mapping.csv

Rename joints in BVH files.

positional arguments:
  input.bvh             BVH files which joints will be renamed.
  mapping.csv           CSV file containing the mapping of old names to new ones
.

optional arguments:
  -h, --help            show this help message and exit
  -v, --ver             show program's version number and exit
  -o [OUT [OUT ...]], --out [OUT [OUT ...]]
                        Destination file paths for BVH files.
                        If no out path is given, or list is shorter than
                        input files, BVH files are overwritten.

Use Unix-style path separators '/' or double backslash '\\' on Windows!

D:\Mocap\BVH\Female\test>bvhrenamejoints female.bvh female.csv
Traceback (most recent call last):
  File "c:\users\kristopher\appdata\local\programs\python\python37-32\lib\runpy.
py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kristopher\appdata\local\programs\python\python37-32\lib\runpy.
py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kristopher\AppData\Local\Programs\Python\Python37-32\Scripts\bv
hrenamejoints.exe\__main__.py", line 9, in <module>
  File "c:\users\kristopher\appdata\local\programs\python\python37-32\lib\site-p
ackages\bvhtoolbox\manipulate\renamejoints.py", line 118, in main
    res.append(rename_joints(bvh_file, mapping, dst_file))
  File "c:\users\kristopher\appdata\local\programs\python\python37-32\lib\site-p
ackages\bvhtoolbox\manipulate\renamejoints.py", line 66, in rename_joints
    if joint in mapping:
NameError: name 'mapping' is not defined

**Comment by OlafHaag** [comment]
It seems I fixed this issue back in August with 5753ed87528f6361697a47e19f4df6e47c3fd196, but didn't push the change to PyPI.
Please update the package and try again.
Since you asked for an example, I'll leave this issue open for now.

**Comment by KristopherPeterson** [comment]
Thanks so much for your help!  Got the mapping working without issue with the update, so no example needed.
