### ISSUE TITLE
bvh2csv throws error NotADirectoryError

### ISSUE THREAD

**Issue by Topper30** [OlafHaag/bvh-toolbox#9]
Using up to date Archlinux
``
bvh2csv /home/olivier/Entry-1F.bvh --rotation --out /home/olivier
Traceback (most recent call last):
  File "/usr/bin/bvh2csv", line 11, in <module>
    load_entry_point('bvhtoolbox==0.1.0', 'console_scripts', 'bvh2csv')()
  File "/usr/lib/python3.8/site-packages/bvhtoolbox/convert/bvh2csv_batch.py", line 107, in main
    os.chdir(src_folder_path)
NotADirectoryError: [Errno 20] Not a directory: '/home/olivier/Entry-1F.bvh'
``

**Comment by OlafHaag** [comment]
Thanks for the report.
I'd suggest 2 things for now.
`bvh2csv --rotation --out /home/olivier /home/olivier/Entry-1F.bvh`

Could you also please try it using the bleeding edge version (v0.1.1)?
`pip install https://github.com/OlafHaag/bvh-toolbox/archive/master.zip`
Though I think the error will still occur.

I'll look into it tomorrow.

**Comment by Topper30** [comment]
The bleeding edge version works !
Good work Olaf !
